version: "3"

services:
  onboarding_mysql:
    container_name: onboarding_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onboarding
    ports:
      - "3306:3306"