version: "3"

services:
  onboarding_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onboarding_api
    depends_on:
      - onboarding_mysql
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - bubble

  onboarding_mysql:
    container_name: onboarding_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onboarding
    ports:
      - "3306:3306"
    networks:
      - bubble

networks:
  bubble:
    external: true