version: "3"

services:
  onboardin_mysql:
    container_name: onboardin_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onboarding
    ports:
      - "3306:3306"